// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4PMttctAA87uniNOnZWI4PXr7IWnZiQ',
    appId: '1:526401567088:web:154632b6a4c63f790637b5',
    messagingSenderId: '526401567088',
    projectId: 'chat-7e1b2',
    authDomain: 'chat-7e1b2.firebaseapp.com',
    storageBucket: 'chat-7e1b2.appspot.com',
    measurementId: 'G-WNSMC6RB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWeS-zz344BcTCPyNBDLao87Wj3nCkfeg',
    appId: '1:526401567088:android:97d71008b74b9be70637b5',
    messagingSenderId: '526401567088',
    projectId: 'chat-7e1b2',
    storageBucket: 'chat-7e1b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZOv6fOsJrTN3umZX0qWEJKd7IwrL0oM',
    appId: '1:526401567088:ios:58f677218b31cd620637b5',
    messagingSenderId: '526401567088',
    projectId: 'chat-7e1b2',
    storageBucket: 'chat-7e1b2.appspot.com',
    iosClientId: '526401567088-l8jdmpotsk7f3a15k4g01i1iddd6690t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZOv6fOsJrTN3umZX0qWEJKd7IwrL0oM',
    appId: '1:526401567088:ios:58f677218b31cd620637b5',
    messagingSenderId: '526401567088',
    projectId: 'chat-7e1b2',
    storageBucket: 'chat-7e1b2.appspot.com',
    iosClientId: '526401567088-l8jdmpotsk7f3a15k4g01i1iddd6690t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
